FROM astral/uv:python3.12-trixie

RUN mkdir /home/app

RUN apt-get update \ 
    && apt-get install -y --no-install-recommends \
    nano \
    gnupg \
    wget

RUN wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(. /etc/os-release && echo $VERSION_CODENAME) main" | tee /etc/apt/sources.list.d/hashicorp.list

RUN apt-get update && apt-get install -y --no-install-recommends terraform

RUN git config --global --add safe.directory /home/app

EXPOSE 8501

ENTRYPOINT [ "tail", "-f", "/dev/null" ]
