FROM astral/uv:python3.12-trixie

RUN mkdir /home/app

RUN apt update \ 
    && apt install -y --no-install-recommends \
    nano

RUN git config --global --add safe.directory /home/app

EXPOSE 8501

ENTRYPOINT [ "tail", "-f", "/dev/null" ]
